import React, { useState } from 'react';
import Dropzone from 'react-dropzone';
import axios from 'axios';
import './App.css';

const plantDiseases = {
  "Apple___Apple_scab": {
    organicCure: "Organic Cure for Apple Scab:\n\n1. Prune infected parts: Prune and remove infected apple tree branches, leaves, and fruit. Bag and dispose of the infected plant material away from the orchard.\n\n2. Organic fungicides: Use organic fungicides that contain ingredients like copper or neem oil. These natural compounds can help suppress apple scab.\n\n3. Proper orchard management: Implement good orchard management practices, including proper pruning, thinning, and adequate spacing between trees. This promotes good air circulation and sunlight penetration, reducing humidity and creating unfavorable conditions for disease development.\n\n4. Sanitation: Remove fallen leaves and fruit from the orchard floor and destroy them to reduce the source of inoculum for future infections.\n\n5. Weed control: Control weeds in the orchard, as they can harbor apple scab spores and contribute to its spread.\n",
    prevention: "Prevention Measures for Apple Scab:\n\n1. Plant resistant varieties: Choose apple tree varieties that are resistant to apple scab. Resistant varieties have genetic traits that provide some level of protection against the disease.\n\n2. Proper pruning and training: Prune apple trees properly to maintain an open canopy and good air circulation. Train the trees to a suitable shape for sunlight penetration and drying of the foliage.\n\n3. Sanitation: Remove and destroy infected plant material, including pruned branches, leaves, and fruit, to reduce the source of inoculum for future infections.\n\n4. Disease-free planting material: Start with disease-free planting material from reputable nurseries.\n\n5. Fungicide applications: Apply fungicides preventively according to a recommended schedule, especially during periods of high disease pressure.\n\n6. Weed control: Keep the orchard free from weeds, as they can serve as hosts for apple scab and contribute to its spread.\n"
  },
  "Apple___Black_rot": {
    organicCure: "Organic Cure for Black Rot:\n\n1. Prune infected parts: Prune and remove infected apple tree branches, cankers, and fruit mummies. Bag and dispose of the infected plant material away from the orchard.\n\n2. Organic fungicides: Use organic fungicides that contain ingredients like copper or neem oil. These natural compounds can help suppress black rot.\n\n3. Proper orchard management: Implement good orchard management practices, including proper pruning, thinning, and adequate spacing between trees. This promotes good air circulation and sunlight penetration, reducing humidity and creating unfavorable conditions for disease development.\n\n4. Sanitation: Remove fallen fruit mummies and infected plant material from the orchard floor and destroy them to reduce the source of inoculum for future infections.\n\n5. Weed control: Control weeds in the orchard, as they can harbor black rot spores and contribute to its spread.\n",
    prevention: "Prevention Measures for Black Rot:\n\n1. Plant resistant varieties: Choose apple tree varieties that are resistant to black rot. Resistant varieties have genetic traits that provide some level of protection against the disease.\n\n2. Proper pruning and training: Prune apple trees properly to maintain an open canopy and good air circulation. Train the trees to a suitable shape for sunlight penetration and drying of the foliage.\n\n3. Sanitation: Remove and destroy infected plant material, including pruned branches, cankers, and fruit mummies, to reduce the source of inoculum for future infections.\n\n4. Disease-free planting material: Start with disease-free planting material from reputable nurseries.\n\n5. Fungicide applications: Apply fungicides preventively according to a recommended schedule, especially during periods of high disease pressure.\n\n6. Weed control: Keep the orchard free from weeds, as they can serve as hosts for black rot and contribute to its spread.\n"
  },
  "Apple___Cedar_apple_rust": {
    organicCure: "Organic Cure for Cedar Apple Rust:\n\n1. Prune infected parts: Prune and remove cedar apple rust galls, cankers, and infected apple tree branches. Bag and dispose of the infected plant material away from the orchard.\n\n2. Organic fungicides: Use organic fungicides that contain ingredients like copper or neem oil. These natural compounds can help suppress cedar apple rust.\n\n3. Proper orchard management: Implement good orchard management practices, including proper pruning, thinning, and adequate spacing between trees. This promotes good air circulation and sunlight penetration, reducing humidity and creating unfavorable conditions for disease development.\n\n4. Sanitation: Remove fallen cedar apple rust galls and infected plant material from the orchard floor and destroy them to reduce the source of inoculum for future infections.\n\n5. Weed control: Control weeds in the orchard, as they can harbor cedar apple rust spores and contribute to its spread.\n",
    prevention: "Prevention Measures for Cedar Apple Rust:\n\n1. Remove nearby cedar trees: If possible, remove or keep a distance from nearby cedar trees, as they act as an alternate host for cedar apple rust.\n\n2. Plant resistant varieties: Choose apple tree varieties that are resistant to cedar apple rust. Resistant varieties have genetic traits that provide some level of protection against the disease.\n\n3. Proper pruning and training: Prune apple trees properly to maintain an open canopy and good air circulation. Train the trees to a suitable shape for sunlight penetration and drying of the foliage.\n\n4. Sanitation: Remove and destroy infected plant material, including pruned branches, galls, cankers, and fallen leaves, to reduce the source of inoculum for future infections.\n\n5. Disease-free planting material: Start with disease-free planting material from reputable nurseries.\n\n6. Fungicide applications: Apply fungicides preventively according to a recommended schedule, especially during periods of high disease pressure.\n\n7. Weed control: Keep the orchard free from weeds, as they can serve as hosts for cedar apple rust and contribute to its spread.\n"
  },
  "Apple___healthy": {
    organicCure: "No cure is required as the plant is healthy.",
    prevention: "Prevention Measures for Keeping Apple Trees Healthy:\n\n1. Disease-resistant varieties: Select apple tree varieties that are known for their resistance to common apple diseases in your area.\n\n2. Proper orchard management: Implement good orchard management practices, including proper pruning, thinning, and adequate spacing between trees. This promotes good air circulation and sunlight penetration, reducing the risk of diseases.\n\n3. Sanitation: Remove and destroy any infected plant material, including pruned branches, cankers, and fallen leaves or fruit, to prevent the spread of diseases.\n\n4. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy tree growth and enhance the plants' natural defense mechanisms.\n\n5. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development. Use irrigation methods that minimize leaf wetness.\n\n6. Weed control: Control weeds in the orchard, as they can compete with apple trees for resources and harbor diseases.\n"
  },
  "Background_without_leaves": {
    organicCure: "No specific cure is required for background without leaves as it is a non-living background image.",
    prevention: "Prevention Measures for Healthy Plant Growth:\n\n1. Plant selection: Choose suitable plant varieties that are adapted to the environmental conditions and resistant to common diseases in your area.\n\n2. Soil preparation: Prepare the soil by adding organic matter, improving drainage, and maintaining proper pH levels to create a favorable environment for plant growth.\n\n3. Proper watering: Provide adequate and appropriate watering to meet the moisture needs of the plants without overwatering or causing water stress.\n\n4. Nutrient management: Maintain proper soil fertility by applying organic fertilizers and amendments to provide essential nutrients for plant growth.\n\n5. Pest control: Implement integrated pest management strategies to control pests and minimize their impact on plant health.\n\n6. Regular monitoring: Monitor plants regularly for any signs of diseases, pests, or nutrient deficiencies, and take prompt action if necessary.\n"
  },
  "Blueberry___healthy": {
    organicCure: "No cure is required as the plant is healthy.",
    prevention: "Prevention Measures for Keeping Blueberry Plants Healthy:\n\n1. Disease-resistant varieties: Select blueberry varieties that are known for their resistance to common blueberry diseases in your area.\n\n2. Sanitation: Remove and destroy any infected plant material, including pruned branches, leaves, and fruit, to prevent the spread of diseases.\n\n3. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n4. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development. Use irrigation methods that minimize leaf wetness.\n\n5. Weed control: Control weeds in the blueberry plantation, as they can compete with blueberry plants for resources and harbor diseases.\n"
  },
  "Cherry___Powdery_mildew": {
    organicCure: "Organic Cure for Powdery Mildew on Cherry Trees:\n\n1. Prune infected parts: Prune and remove infected cherry tree branches, leaves, and fruit. Bag and dispose of the infected plant material away from the orchard.\n\n2. Organic fungicides: Use organic fungicides that contain ingredients like sulfur or potassium bicarbonate. These natural compounds can help suppress powdery mildew.\n\n3. Proper orchard management: Implement good orchard management practices, including proper pruning, thinning, and adequate spacing between trees. This promotes good air circulation and sunlight penetration, reducing humidity and creating unfavorable conditions for disease development.\n\n4. Sanitation: Remove fallen leaves and fruit from the orchard floor and destroy them to reduce the source of inoculum for future infections.\n\n5. Weed control: Control weeds in the orchard, as they can harbor powdery mildew spores and contribute to its spread.\n",
    prevention: "Prevention Measures for Powdery Mildew on Cherry Trees:\n\n1. Plant resistant varieties: Choose cherry tree varieties that are resistant to powdery mildew. Resistant varieties have genetic traits that provide some level of protection against the disease.\n\n2. Proper pruning and training: Prune cherry trees properly to maintain an open canopy and good air circulation. Train the trees to a suitable shape for sunlight penetration and drying of the foliage.\n\n3. Sanitation: Remove and destroy infected plant material, including pruned branches, leaves, and fruit, to reduce the source of inoculum for future infections.\n\n4. Disease-free planting material: Start with disease-free planting material from reputable nurseries.\n\n5. Fungicide applications: Apply fungicides preventively according to a recommended schedule, especially during periods of high disease pressure.\n\n6. Weed control: Keep the orchard free from weeds, as they can serve as hosts for powdery mildew and contribute to its spread.\n"
  },
  "Cherry___healthy": {
    organicCure: "No cure is required as the plant is healthy.",
    prevention: "Prevention Measures for Keeping Cherry Trees Healthy:\n\n1. Disease-resistant varieties: Select cherry tree varieties that are known for their resistance to common cherry diseases in your area.\n\n2. Proper pruning and training: Prune cherry trees properly to maintain an open canopy and good air circulation. Train the trees to a suitable shape for sunlight penetration and drying of the foliage.\n\n3. Sanitation: Remove and destroy any infected plant material, including pruned branches, leaves, and fruit, to prevent the spread of diseases.\n\n4. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy tree growth and enhance the plants' natural defense mechanisms.\n\n5. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development. Use irrigation methods that minimize leaf wetness.\n\n6. Weed control: Control weeds in the orchard, as they can compete with cherry trees for resources and harbor diseases.\n"
  },
  "Corn___Cercospora_leaf_spot Gray_leaf_spot": {
    organicCure: "Organic Cure for Cercospora Leaf Spot (Gray Leaf Spot) on Corn:\n\n1. Crop rotation: Practice crop rotation with non-host plants to reduce the build-up of disease-causing pathogens in the soil.\n\n2. Organic fungicides: Use organic fungicides that contain ingredients like copper or plant extracts with antifungal properties. These natural compounds can help suppress Cercospora leaf spot.\n\n3. Planting resistant varieties: Choose corn varieties that are resistant to Cercospora leaf spot.\n\n4. Proper field sanitation: Remove and destroy infected corn debris after harvest to reduce the source of inoculum for future infections.\n\n5. Proper spacing: Plant corn at recommended spacing to promote good air circulation and reduce humidity, creating unfavorable conditions for disease development.\n\n6. Weed control: Control weeds in the cornfield, as they can compete with corn for resources and create a conducive environment for disease development.\n",
    prevention: "Prevention Measures for Cercospora Leaf Spot (Gray Leaf Spot) on Corn:\n\n1. Crop rotation: Avoid planting corn in the same field consecutively. Rotate with non-host crops to break the disease cycle.\n\n2. Disease-free seeds: Use certified disease-free corn seeds obtained from reputable sources.\n\n3. Proper field sanitation: Remove and destroy infected corn debris after harvest to reduce the source of inoculum for future infections.\n\n4. Planting resistant varieties: Choose corn varieties that are resistant to Cercospora leaf spot.\n\n5. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n6. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n\n7. Weed control: Control weeds in the cornfield, as they can compete with corn for resources and create a conducive environment for disease development.\n"
  },
  "Corn___Common_rust": {
    organicCure: "Organic Cure for Common Rust on Corn:\n\n1. Crop rotation: Practice crop rotation with non-host plants to reduce the build-up of disease-causing pathogens in the soil.\n\n2. Organic fungicides: Use organic fungicides that contain ingredients like copper or plant extracts with antifungal properties. These natural compounds can help suppress common rust.\n\n3. Planting resistant varieties: Choose corn varieties that are resistant to common rust.\n\n4. Proper field sanitation: Remove and destroy infected corn debris after harvest to reduce the source of inoculum for future infections.\n\n5. Proper spacing: Plant corn at recommended spacing to promote good air circulation and reduce humidity, creating unfavorable conditions for disease development.\n\n6. Weed control: Control weeds in the cornfield, as they can compete with corn for resources and create a conducive environment for disease development.\n",
    prevention: "Prevention Measures for Common Rust on Corn:\n\n1. Crop rotation: Avoid planting corn in the same field consecutively. Rotate with non-host crops to break the disease cycle.\n\n2. Disease-free seeds: Use certified disease-free corn seeds obtained from reputable sources.\n\n3. Proper field sanitation: Remove and destroy infected corn debris after harvest to reduce the source of inoculum for future infections.\n\n4. Planting resistant varieties: Choose corn varieties that are resistant to common rust.\n\n5. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n6. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n\n7. Weed control: Control weeds in the cornfield, as they can compete with corn for resources and create a conducive environment for disease development.\n"
  },
  "Corn___Northern_Leaf_Blight": {
    organicCure: "Organic Cure for Northern Leaf Blight on Corn:\n\n1. Crop rotation: Practice crop rotation with non-host plants to reduce the build-up of disease-causing pathogens in the soil.\n\n2. Organic fungicides: Use organic fungicides that contain ingredients like copper or plant extracts with antifungal properties. These natural compounds can help suppress northern leaf blight.\n\n3. Planting resistant varieties: Choose corn varieties that are resistant to northern leaf blight.\n\n4. Proper field sanitation: Remove and destroy infected corn debris after harvest to reduce the source of inoculum for future infections.\n\n5. Proper spacing: Plant corn at recommended spacing to promote good air circulation and reduce humidity, creating unfavorable conditions for disease development.\n\n6. Weed control: Control weeds in the cornfield, as they can compete with corn for resources and create a conducive environment for disease development.\n",
    prevention: "Prevention Measures for Northern Leaf Blight on Corn:\n\n1. Crop rotation: Avoid planting corn in the same field consecutively. Rotate with non-host crops to break the disease cycle.\n\n2. Disease-free seeds: Use certified disease-free corn seeds obtained from reputable sources.\n\n3. Proper field sanitation: Remove and destroy infected corn debris after harvest to reduce the source of inoculum for future infections.\n\n4. Planting resistant varieties: Choose corn varieties that are resistant to northern leaf blight.\n\n5. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n6. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n\n7. Weed control: Control weeds in the cornfield, as they can compete with corn for resources and create a conducive environment for disease development.\n"
  },
  "Corn___healthy": {
    organicCure: "No cure is required as the plant is healthy.",
    prevention: "Prevention Measures for Keeping Corn Plants Healthy:\n\n1. Disease-resistant varieties: Select corn varieties that are known for their resistance to common corn diseases in your area.\n\n2. Proper planting density: Plant corn at the recommended density to avoid overcrowding, which can create a favorable environment for disease development.\n\n3. Crop rotation: Rotate corn with non-host crops to break the disease cycle and reduce the build-up of pathogens in the soil.\n\n4. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n5. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n\n6. Weed control: Control weeds in the cornfield, as they can compete with corn for resources and harbor diseases.\n"
  },
  "Grape___Black_rot": {
    organicCure: "Organic Cure for Black Rot on Grapevines:\n\n1. Prune infected parts: Prune and remove infected grapevine canes, leaves, and fruit clusters. Dispose of the infected plant material away from the vineyard.\n\n2. Organic fungicides: Use organic fungicides that contain ingredients like copper or plant extracts with antifungal properties. These natural compounds can help suppress black rot.\n\n3. Proper vineyard management: Implement good vineyard management practices, including proper pruning, trellising, and canopy management. This promotes good air circulation and sunlight penetration, reducing humidity and creating unfavorable conditions for disease development.\n\n4. Sanitation: Remove fallen leaves, mummies, and pruned canes from the vineyard floor and destroy them to reduce the source of inoculum for future infections.\n\n5. Weed control: Control weeds in the vineyard, as they can compete with grapevines for resources and contribute to disease development.\n",
    prevention: "Prevention Measures for Black Rot on Grapevines:\n\n1. Plant resistant varieties: Choose grapevine varieties that are resistant to black rot. Resistant varieties have genetic traits that provide some level of protection against the disease.\n\n2. Proper pruning and training: Prune and train grapevines properly to maintain an open canopy and good air circulation. This helps reduce humidity and create unfavorable conditions for disease development.\n\n3. Sanitation: Remove and destroy infected plant material, including pruned canes, leaves, and fruit clusters, to reduce the source of inoculum for future infections.\n\n4. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy vine growth and enhance the plants' natural defense mechanisms.\n\n5. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n\n6. Weed control: Control weeds in the vineyard, as they can compete with grapevines for resources and contribute to disease development.\n"
  },
  "Grape___Esca_(Black_Measles)": {
    organicCure: "Organic Cure for Esca (Black Measles) on Grapevines:\n\n1. Prune infected parts: Prune and remove infected grapevine canes, leaves, and fruit clusters. Dispose of the infected plant material away from the vineyard.\n\n2. Organic fungicides: Use organic fungicides that contain ingredients like copper or plant extracts with antifungal properties. These natural compounds can help suppress Esca.\n\n3. Proper vineyard management: Implement good vineyard management practices, including proper pruning, trellising, and canopy management. This promotes good air circulation and sunlight penetration, reducing humidity and creating unfavorable conditions for disease development.\n\n4. Sanitation: Remove fallen leaves, mummies, and pruned canes from the vineyard floor and destroy them to reduce the source of inoculum for future infections.\n\n5. Weed control: Control weeds in the vineyard, as they can compete with grapevines for resources and contribute to disease development.\n",
    prevention: "Prevention Measures for Esca (Black Measles) on Grapevines:\n\n1. Plant resistant varieties: Choose grapevine varieties that are resistant to Esca. Resistant varieties have genetic traits that provide some level of protection against the disease.\n\n2. Proper pruning and training: Prune and train grapevines properly to maintain an open canopy and good air circulation. This helps reduce humidity and create unfavorable conditions for disease development.\n\n3. Sanitation: Remove and destroy infected plant material, including pruned canes, leaves, and fruit clusters, to reduce the source of inoculum for future infections.\n\n4. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy vine growth and enhance the plants' natural defense mechanisms.\n\n5. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n\n6. Weed control: Control weeds in the vineyard, as they can compete with grapevines for resources and contribute to disease development.\n"
  },
  "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": {
    organicCure: "Organic Cure for Leaf Blight (Isariopsis Leaf Spot) on Grapevines:\n\n1. Prune infected parts: Prune and remove infected grapevine canes, leaves, and fruit clusters. Dispose of the infected plant material away from the vineyard.\n\n2. Organic fungicides: Use organic fungicides that contain ingredients like copper or plant extracts with antifungal properties. These natural compounds can help suppress leaf blight.\n\n3. Proper vineyard management: Implement good vineyard management practices, including proper pruning, trellising, and canopy management. This promotes good air circulation and sunlight penetration, reducing humidity and creating unfavorable conditions for disease development.\n\n4. Sanitation: Remove fallen leaves, mummies, and pruned canes from the vineyard floor and destroy them to reduce the source of inoculum for future infections.\n\n5. Weed control: Control weeds in the vineyard, as they can compete with grapevines for resources and contribute to disease development.\n",
    prevention: "Prevention Measures for Leaf Blight (Isariopsis Leaf Spot) on Grapevines:\n\n1. Plant resistant varieties: Choose grapevine varieties that are resistant to leaf blight. Resistant varieties have genetic traits that provide some level of protection against the disease.\n\n2. Proper pruning and training: Prune and train grapevines properly to maintain an open canopy and good air circulation. This helps reduce humidity and create unfavorable conditions for disease development.\n\n3. Sanitation: Remove and destroy infected plant material, including pruned canes, leaves, and fruit clusters, to reduce the source of inoculum for future infections.\n\n4. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy vine growth and enhance the plants' natural defense mechanisms.\n\n5. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n\n6. Weed control: Control weeds in the vineyard, as they can compete with grapevines for resources and contribute to disease development.\n"
  },
  "Grape___healthy": {
    organicCure: "No cure is required as the plant is healthy.",
    prevention: "Prevention Measures for Keeping Grapevines Healthy:\n\n1. Disease-resistant varieties: Select grapevine varieties that are known for their resistance to common grape diseases in your area.\n\n2. Proper pruning and training: Prune and train grapevines properly to maintain an open canopy and good air circulation. This helps reduce humidity and create unfavorable conditions for disease development.\n\n3. Sanitation: Remove and destroy infected plant material, including pruned canes, leaves, and fruit clusters, to reduce the source of inoculum for future infections.\n\n4. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy vine growth and enhance the plants' natural defense mechanisms.\n\n5. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n\n6. Weed control: Control weeds in the vineyard, as they can compete with grapevines for resources and contribute to disease development.\n"
  },
  "Orange___Haunglongbing_(Citrus_greening)": {
    organicCure: "Organic Cure for Huanglongbing (Citrus Greening) on Orange Trees:\n\n1. Prune infected parts: Prune and remove infected branches, leaves, and fruits. Dispose of the infected plant material away from the orchard.\n\n2. Biological control agents: Use beneficial insects or microbial agents that target the insect vectors of citrus greening, such as psyllids.\n\n3. Soil improvement: Implement soil management practices, such as adding organic matter and improving soil drainage, to promote tree health and vigor.\n\n4. Nutritional support: Apply organic fertilizers or soil amendments that promote the overall health and immunity of the orange trees.\n\n5. Sanitation: Remove fallen leaves, fruits, and debris from the orchard to reduce the presence of psyllid vectors and the disease-causing bacteria.\n\n6. Monitoring and early detection: Regularly inspect orange trees for symptoms of citrus greening and take immediate action if any signs are observed.\n",
    prevention: "Prevention Measures for Huanglongbing (Citrus Greening) on Orange Trees:\n\n1. Use disease-free planting material: Obtain certified disease-free orange trees from reputable nurseries.\n\n2. Psyllid control: Implement a psyllid control program using insecticides or beneficial insects that target the psyllid vectors of citrus greening.\n\n3. Sanitation: Remove and destroy infected plant material, including fallen leaves, fruits, and debris, to reduce the source of inoculum for future infections.\n\n4. Nutritional support: Maintain proper soil fertility and provide balanced nutrition to promote tree health and enhance the plants' natural defense mechanisms.\n\n5. Monitoring and early detection: Regularly inspect orange trees for symptoms of citrus greening and take immediate action if any signs are observed.\n\n6. Quarantine measures: Implement quarantine measures to prevent the introduction and spread of citrus greening in new areas.\n"
  },
  "Peach___Bacterial_spot": {
    organicCure: "Organic Cure for Bacterial Spot on Peach Trees:\n\n1. Prune infected parts: Prune and remove infected branches, twigs, and leaves. Dispose of the infected plant material away from the orchard.\n\n2. Copper-based sprays: Use organic copper-based sprays or bactericides approved for organic farming to suppress bacterial spot.\n\n3. Sanitation: Remove fallen leaves, fruits, and debris from the orchard to reduce the source of inoculum for future infections.\n\n4. Nutritional support: Apply organic fertilizers or soil amendments that promote the overall health and immunity of the peach trees.\n\n5. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n\n6. Monitoring and early detection: Regularly inspect peach trees for symptoms of bacterial spot and take immediate action if any signs are observed.\n",
    prevention: "Prevention Measures for Bacterial Spot on Peach Trees:\n\n1. Use disease-resistant varieties: Select peach tree varieties that are resistant to bacterial spot.\n\n2. Pruning and thinning: Prune peach trees to promote good air circulation and sunlight penetration. Thin out excess branches to reduce humidity and create unfavorable conditions for disease development.\n\n3. Sanitation: Remove and destroy infected plant material, including fallen leaves, fruits, and debris, to reduce the source of inoculum for future infections.\n\n4. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote tree health and enhance the plants' natural defense mechanisms.\n\n5. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n\n6. Monitoring and early detection: Regularly inspect peach trees for symptoms of bacterial spot and take immediate action if any signs are observed.\n"
  },
  "Peach___healthy": {
    organicCure: "No cure is required as the plant is healthy.",
    prevention: "Prevention Measures for Keeping Peach Trees Healthy:\n\n1. Disease-resistant varieties: Select peach tree varieties that are known for their resistance to common peach diseases in your area.\n\n2. Proper pruning and thinning: Prune peach trees to promote good air circulation and sunlight penetration. Thin out excess branches to reduce humidity and create unfavorable conditions for disease development.\n\n3. Sanitation: Remove fallen leaves, fruits, and debris from the orchard to reduce the source of inoculum for future infections.\n\n4. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote tree health and enhance the plants' natural defense mechanisms.\n\n5. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n\n6. Weed control: Control weeds around the base of peach trees, as they can compete for resources and harbor pests and diseases.\n"
  },
  "Pepper,_bell___Bacterial_spot": {
    organicCure: "Organic Cure for Bacterial Spot on Bell Peppers:\n\n1. Prune infected parts: Prune and remove infected leaves, stems, and fruits. Dispose of the infected plant material away from the garden.\n\n2. Copper-based sprays: Use organic copper-based sprays or bactericides approved for organic gardening to suppress bacterial spot.\n\n3. Sanitation: Remove fallen leaves, fruits, and debris from the garden to reduce the source of inoculum for future infections.\n\n4. Crop rotation: Rotate bell peppers with non-host crops to break the disease cycle and reduce the build-up of pathogens in the soil.\n\n5. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n6. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n",
    prevention: "Prevention Measures for Bacterial Spot on Bell Peppers:\n\n1. Use disease-resistant varieties: Select bell pepper varieties that are resistant to bacterial spot.\n\n2. Proper spacing: Plant bell peppers at the recommended spacing to ensure good air circulation and minimize humidity.\n\n3. Sanitation: Remove and destroy infected plant material, including fallen leaves, fruits, and debris, to reduce the source of inoculum for future infections.\n\n4. Crop rotation: Rotate bell peppers with non-host crops to break the disease cycle and reduce the build-up of pathogens in the soil.\n\n5. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n6. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n"
  },
  "Pepper,_bell___healthy": {
    organicCure: "No cure is required as the plant is healthy.",
    prevention: "Prevention Measures for Keeping Bell Peppers Healthy:\n\n1. Use disease-resistant varieties: Select bell pepper varieties that are known for their resistance to common pepper diseases in your area.\n\n2. Proper spacing: Plant bell peppers at the recommended spacing to ensure good air circulation and minimize humidity.\n\n3. Sanitation: Remove fallen leaves, fruits, and debris from the garden to reduce the source of inoculum for future infections.\n\n4. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n5. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n\n6. Weed control: Control weeds in the garden, as they can compete with bell peppers for resources and contribute to disease development.\n"
  },
  "Potato___Early_blight": {
    organicCure: "Organic Cure for Early Blight on Potato Plants:\n\n1. Prune infected parts: Prune and remove infected leaves, stems, and fruits. Dispose of the infected plant material away from the garden.\n\n2. Organic fungicides: Use organic fungicides that contain ingredients like copper or plant extracts with antifungal properties. These natural compounds can help suppress early blight.\n\n3. Crop rotation: Rotate potatoes with non-host crops to break the disease cycle and reduce the build-up of pathogens in the soil.\n\n4. Sanitation: Remove fallen leaves, fruits, and debris from the garden to reduce the source of inoculum for future infections.\n\n5. Proper spacing: Plant potato plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n6. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n",
    prevention: "Prevention Measures for Early Blight on Potato Plants:\n\n1. Use disease-resistant varieties: Select potato varieties that are resistant to early blight.\n\n2. Crop rotation: Rotate potatoes with non-host crops to break the disease cycle and reduce the build-up of pathogens in the soil.\n\n3. Sanitation: Remove and destroy infected plant material, including fallen leaves, fruits, and debris, to reduce the source of inoculum for future infections.\n\n4. Proper spacing: Plant potato plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n5. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n6. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n"
  },
  "Potato___Late_blight": {
    organicCure: "Organic Cure for Late Blight on Potato Plants:\n\n1. Prune infected parts: Prune and remove infected leaves, stems, and fruits. Dispose of the infected plant material away from the garden.\n\n2. Organic fungicides: Use organic fungicides that contain ingredients like copper or plant extracts with antifungal properties. These natural compounds can help suppress late blight.\n\n3. Crop rotation: Rotate potatoes with non-host crops to break the disease cycle and reduce the build-up of pathogens in the soil.\n\n4. Sanitation: Remove fallen leaves, fruits, and debris from the garden to reduce the source of inoculum for future infections.\n\n5. Proper spacing: Plant potato plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n6. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n",
    prevention: "Prevention Measures for Late Blight on Potato Plants:\n\n1. Use disease-resistant varieties: Select potato varieties that are resistant to late blight.\n\n2. Crop rotation: Rotate potatoes with non-host crops to break the disease cycle and reduce the build-up of pathogens in the soil.\n\n3. Sanitation: Remove and destroy infected plant material, including fallen leaves, fruits, and debris, to reduce the source of inoculum for future infections.\n\n4. Proper spacing: Plant potato plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n5. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n6. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n"
  },
  "Potato___healthy": {
    organicCure: "No cure is required as the plant is healthy.",
    prevention: "Prevention Measures for Keeping Potato Plants Healthy:\n\n1. Use disease-resistant varieties: Select potato varieties that are known for their resistance to common potato diseases in your area.\n\n2. Crop rotation: Rotate potatoes with non-host crops to break the disease cycle and reduce the build-up of pathogens in the soil.\n\n3. Sanitation: Remove fallen leaves, fruits, and debris from the garden to reduce the source of inoculum for future infections.\n\n4. Proper spacing: Plant potato plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n5. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n6. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n"
  },
  "Raspberry___healthy": {
    organicCure: "No cure is required as the plant is healthy.",
    prevention: "Prevention Measures for Keeping Raspberry Plants Healthy:\n\n1. Use disease-resistant varieties: Select raspberry varieties that are known for their resistance to common raspberry diseases in your area.\n\n2. Proper pruning: Prune raspberry canes to maintain an open canopy and good air circulation. This helps reduce humidity and create unfavorable conditions for disease development.\n\n3. Sanitation: Remove and destroy infected plant material, including pruned canes and leaves, to reduce the source of inoculum for future infections.\n\n4. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n5. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n\n6. Weed control: Control weeds around the base of raspberry plants, as they can compete for resources and harbor pests and diseases.\n"
  },
  "Soybean___healthy": {
    organicCure: "No cure is required as the plant is healthy.",
    prevention: "Prevention Measures for Keeping Soybean Plants Healthy:\n\n1. Use disease-resistant varieties: Select soybean varieties that are known for their resistance to common soybean diseases in your area.\n\n2. Crop rotation: Rotate soybeans with non-host crops to break the disease cycle and reduce the build-up of pathogens in the soil.\n\n3. Sanitation: Remove and destroy infected plant material, including fallen leaves, pods, and debris, to reduce the source of inoculum for future infections.\n\n4. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n5. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n\n6. Weed control: Control weeds in soybean fields, as they can compete for resources and contribute to disease development.\n"
  },
  "Squash___Powdery_mildew": {
    organicCure: "Organic Cure for Powdery Mildew on Squash Plants:\n\n1. Milk spray: Mix milk and water in a 1:9 ratio (1 part milk to 9 parts water) and spray the solution on the affected squash plants. The proteins in milk have antifungal properties that can help suppress powdery mildew.\n\n2. Neem oil spray: Apply organic neem oil spray to the affected plants, following the instructions on the product label.\n\n3. Baking soda spray: Mix 1 tablespoon of baking soda, 1 teaspoon of liquid soap, and 1 gallon of water. Spray the solution on the affected plants.\n\n4. Sulfur-based fungicides: Use organic sulfur-based fungicides approved for powdery mildew control.\n\n5. Proper spacing: Plant squash plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n6. Sanitation: Remove and destroy infected plant material, including leaves and debris, to reduce the source of inoculum for future infections.\n",
    prevention: "Prevention Measures for Powdery Mildew on Squash Plants:\n\n1. Use disease-resistant varieties: Select squash varieties that are resistant to powdery mildew.\n\n2. Proper spacing: Plant squash plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n3. Sanitation: Remove and destroy infected plant material, including leaves and debris, to reduce the source of inoculum for future infections.\n\n4. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n\n5. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n6. Weed control: Control weeds around the base of squash plants, as they can compete for resources and contribute to disease development.\n"
  },
  "Strawberry___Leaf_scorch": {
    organicCure: "Organic Cure for Leaf Scorch on Strawberry Plants:\n\n1. Remove infected leaves: Prune and remove infected leaves. Dispose of the infected plant material away from the strawberry patch.\n\n2. Copper-based sprays: Use organic copper-based sprays or bactericides approved for organic gardening to suppress leaf scorch.\n\n3. Sanitation: Remove fallen leaves, fruits, and debris from the strawberry patch to reduce the source of inoculum for future infections.\n\n4. Proper spacing: Plant strawberry plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n5. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n6. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n",
    prevention: "Prevention Measures for Leaf Scorch on Strawberry Plants:\n\n1. Use disease-resistant varieties: Select strawberry varieties that are resistant to leaf scorch.\n\n2. Proper spacing: Plant strawberry plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n3. Sanitation: Remove and destroy infected plant material, including fallen leaves, fruits, and debris, to reduce the source of inoculum for future infections.\n\n4. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n\n5. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n6. Weed control: Control weeds in the strawberry patch, as they can compete for resources and contribute to disease development.\n"
  },
  "Strawberry___healthy": {
    organicCure: "No cure is required as the plant is healthy.",
    prevention: "Prevention Measures for Keeping Strawberry Plants Healthy:\n\n1. Use disease-resistant varieties: Select strawberry varieties that are known for their resistance to common strawberry diseases in your area.\n\n2. Proper spacing: Plant strawberry plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n3. Sanitation: Remove and destroy infected plant material, including fallen leaves, fruits, and debris, to reduce the source of inoculum for future infections.\n\n4. Irrigation management: Avoid over-irrigation and waterlogging, as excessive moisture can promote disease development.\n\n5. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n6. Weed control: Control weeds in the strawberry patch, as they can compete for resources and contribute to disease development.\n"
  },
  "Tomato___Bacterial_spot": {
    organicCure: "Organic Cure for Bacterial Spot on Tomato Plants:\n\n1. Copper-based sprays: Use organic copper-based sprays or bactericides approved for organic gardening to suppress bacterial spot.\n\n2. Serenade® Garden Disease Control: Apply Serenade® Garden Disease Control, an organic biofungicide that contains Bacillus subtilis, following the instructions on the product label.\n\n3. Neem oil spray: Apply organic neem oil spray to the affected plants, following the instructions on the product label.\n\n4. Proper spacing: Plant tomato plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n5. Sanitation: Remove and destroy infected plant material, including leaves and debris, to reduce the source of inoculum for future infections.\n",
    prevention: "Prevention Measures for Bacterial Spot on Tomato Plants:\n\n1. Use disease-resistant varieties: Select tomato varieties that are resistant to bacterial spot.\n\n2. Proper spacing: Plant tomato plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n3. Sanitation: Remove and destroy infected plant material, including leaves and debris, to reduce the source of inoculum for future infections.\n\n4. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n5. Irrigation management: Avoid overhead irrigation and waterlogging, as excessive moisture can promote disease development.\n\n6. Weed control: Control weeds around the base of tomato plants, as they can compete for resources and contribute to disease development.\n"
  },
  "Tomato___Early_blight": {
    organicCure: "Organic Cure for Early Blight on Tomato Plants:\n\n1. Baking soda spray: Mix 1 tablespoon of baking soda, 1 teaspoon of liquid soap, and 1 gallon of water. Spray the solution on the affected plants.\n\n2. Neem oil spray: Apply organic neem oil spray to the affected plants, following the instructions on the product label.\n\n3. Serenade® Garden Disease Control: Apply Serenade® Garden Disease Control, an organic biofungicide that contains Bacillus subtilis, following the instructions on the product label.\n\n4. Proper spacing: Plant tomato plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n5. Sanitation: Remove and destroy infected plant material, including leaves and debris, to reduce the source of inoculum for future infections.\n",
    prevention: "Prevention Measures for Early Blight on Tomato Plants:\n\n1. Use disease-resistant varieties: Select tomato varieties that are resistant to early blight.\n\n2. Proper spacing: Plant tomato plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n3. Sanitation: Remove and destroy infected plant material, including leaves and debris, to reduce the source of inoculum for future infections.\n\n4. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n5. Irrigation management: Avoid overhead irrigation and waterlogging, as excessive moisture can promote disease development.\n\n6. Weed control: Control weeds around the base of tomato plants, as they can compete for resources and contribute to disease development.\n"
  },
  "Tomato___Late_blight": {
    organicCure: "Organic Cure for Late Blight on Tomato Plants:\n\n1. Copper-based sprays: Use organic copper-based sprays or bactericides approved for organic gardening to suppress late blight.\n\n2. Serenade® Garden Disease Control: Apply Serenade® Garden Disease Control, an organic biofungicide that contains Bacillus subtilis, following the instructions on the product label.\n\n3. Neem oil spray: Apply organic neem oil spray to the affected plants, following the instructions on the product label.\n\n4. Proper spacing: Plant tomato plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n5. Sanitation: Remove and destroy infected plant material, including leaves and debris, to reduce the source of inoculum for future infections.\n",
    prevention: "Prevention Measures for Late Blight on Tomato Plants:\n\n1. Use disease-resistant varieties: Select tomato varieties that are resistant to late blight.\n\n2. Proper spacing: Plant tomato plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n3. Sanitation: Remove and destroy infected plant material, including leaves and debris, to reduce the source of inoculum for future infections.\n\n4. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n5. Irrigation management: Avoid overhead irrigation and waterlogging, as excessive moisture can promote disease development.\n\n6. Weed control: Control weeds around the base of tomato plants, as they can compete for resources and contribute to disease development.\n"
  },
  "Tomato___Leaf_Mold": {
    organicCure: "Organic Cure for Leaf Mold on Tomato Plants:\n\n1. Serenade® Garden Disease Control: Apply Serenade® Garden Disease Control, an organic biofungicide that contains Bacillus subtilis, following the instructions on the product label.\n\n2. Neem oil spray: Apply organic neem oil spray to the affected plants, following the instructions on the product label.\n\n3. Proper spacing: Plant tomato plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n4. Sanitation: Remove and destroy infected plant material, including leaves and debris, to reduce the source of inoculum for future infections.\n",
    prevention: "Prevention Measures for Leaf Mold on Tomato Plants:\n\n1. Use disease-resistant varieties: Select tomato varieties that are resistant to leaf mold.\n\n2. Proper spacing: Plant tomato plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n3. Sanitation: Remove and destroy infected plant material, including leaves and debris, to reduce the source of inoculum for future infections.\n\n4. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n5. Irrigation management: Avoid overhead irrigation and waterlogging, as excessive moisture can promote disease development.\n\n6. Weed control: Control weeds around the base of tomato plants, as they can compete for resources and contribute to disease development.\n"
  },
  "Tomato___Septoria_leaf_spot": {
    organicCure: "Organic Cure for Septoria Leaf Spot on Tomato Plants:\n\n1. Serenade® Garden Disease Control: Apply Serenade® Garden Disease Control, an organic biofungicide that contains Bacillus subtilis, following the instructions on the product label.\n\n2. Neem oil spray: Apply organic neem oil spray to the affected plants, following the instructions on the product label.\n\n3. Baking soda spray: Mix 1 tablespoon of baking soda, 1 teaspoon of liquid soap, and 1 gallon of water. Spray the solution on the affected plants.\n\n4. Proper spacing: Plant tomato plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n5. Sanitation: Remove and destroy infected plant material, including leaves and debris, to reduce the source of inoculum for future infections.\n",
    prevention: "Prevention Measures for Septoria Leaf Spot on Tomato Plants:\n\n1. Use disease-resistant varieties: Select tomato varieties that are resistant to Septoria leaf spot.\n\n2. Proper spacing: Plant tomato plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n3. Sanitation: Remove and destroy infected plant material, including leaves and debris, to reduce the source of inoculum for future infections.\n\n4. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n5. Irrigation management: Avoid overhead irrigation and waterlogging, as excessive moisture can promote disease development.\n\n6. Weed control: Control weeds around the base of tomato plants, as they can compete for resources and contribute to disease development.\n"
  },
  "Tomato___Spider_mites Two-spotted_spider_mite": {
    organicCure: "Organic Cure for Two-Spotted Spider Mite on Tomato Plants:\n\n1. Water spray: Spray the affected plants with a strong stream of water to dislodge and remove the spider mites.\n\n2. Insecticidal soap: Apply organic insecticidal soap to the affected plants, following the instructions on the product label.\n\n3. Neem oil spray: Apply organic neem oil spray to the affected plants, following the instructions on the product label.\n\n4. Predatory mites: Introduce predatory mites, such as Phytoseiulus persimilis, to control the two-spotted spider mite population.\n\n5. Reflective mulch: Use reflective mulch around tomato plants to repel spider mites.\n",
    prevention: "Prevention Measures for Two-Spotted Spider Mite on Tomato Plants:\n\n1. Monitor plants: Regularly inspect tomato plants for early signs of two-spotted spider mite infestation, such as stippling and webbing.\n\n2. Proper spacing: Plant tomato plants at the recommended spacing to ensure good air circulation and minimize humidity, which can discourage spider mite infestation.\n\n3. Avoid excessive nitrogen: High nitrogen levels can attract spider mites. Maintain balanced nutrition and avoid excessive nitrogen fertilization.\n\n4. Weed control: Remove weeds from the garden area, as they can harbor spider mites and serve as a source of infestation.\n\n5. Introduce beneficial insects: Encourage the presence of predatory insects, such as ladybugs and lacewings, which feed on spider mites.\n"
  },
  "Tomato___Target_Spot": {
    organicCure: "Organic Cure for Target Spot on Tomato Plants:\n\n1. Serenade® Garden Disease Control: Apply Serenade® Garden Disease Control, an organic biofungicide that contains Bacillus subtilis, following the instructions on the product label.\n\n2. Neem oil spray: Apply organic neem oil spray to the affected plants, following the instructions on the product label.\n\n3. Baking soda spray: Mix 1 tablespoon of baking soda, 1 teaspoon of liquid soap, and 1 gallon of water. Spray the solution on the affected plants.\n\n4. Proper spacing: Plant tomato plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n5. Sanitation: Remove and destroy infected plant material, including leaves and debris, to reduce the source of inoculum for future infections.\n",
    prevention: "Prevention Measures for Target Spot on Tomato Plants:\n\n1. Use disease-resistant varieties: Select tomato varieties that are resistant to target spot.\n\n2. Proper spacing: Plant tomato plants at the recommended spacing to ensure good air circulation and minimize humidity.\n\n3. Sanitation: Remove and destroy infected plant material, including leaves and debris, to reduce the source of inoculum for future infections.\n\n4. Balanced nutrition: Maintain proper soil fertility and provide balanced nutrition to promote healthy plant growth and enhance the plants' natural defense mechanisms.\n\n5. Irrigation management: Avoid overhead irrigation and waterlogging, as excessive moisture can promote disease development.\n\n6. Weed control: Control weeds around the base of tomato plants, as they can compete for resources and contribute to disease development.\n"
  },
  "Tomato___Tomato_Yellow_Leaf_Curl_Virus": {
    organicCure: "No organic cure is available for Tomato Yellow Leaf Curl Virus (TYLCV). It is primarily managed through prevention measures.",
    prevention: "Prevention Measures for Tomato Yellow Leaf Curl Virus (TYLCV):\n\n1. Use disease-resistant varieties: Select tomato varieties that are resistant to TYLCV.\n\n2. Vector control: Manage the population of whiteflies, the vectors of TYLCV, through physical barriers, such as insect netting, and use of yellow sticky traps.\n\n3. Sanitation: Remove and destroy infected plant material, including leaves and debris, to reduce the source of inoculum for future infections.\n\n4. Weed control: Control weeds in and around the tomato garden, as they can harbor whiteflies.\n\n5. Quarantine measures: Avoid introducing infected plants or plant material into the garden, and practice strict quarantine protocols for new plant acquisitions.\n"
  },
  "Tomato___Tomato_mosaic_virus": {
    organicCure: "No organic cure is available for Tomato Mosaic Virus (TMV). It is primarily managed through prevention measures.",
    prevention: "Prevention Measures for Tomato Mosaic Virus (TMV):\n\n1. Use disease-resistant varieties: Select tomato varieties that are resistant to TMV.\n\n2. Vector control: Manage the population of aphids, the vectors of TMV, through physical barriers, such as insect netting, and use of yellow sticky traps.\n\n3. Sanitation: Remove and destroy infected plant material, including leaves and debris, to reduce the source of inoculum for future infections.\n\n4. Weed control: Control weeds in and around the tomato garden, as they can harbor aphids.\n\n5. Quarantine measures: Avoid introducing infected plants or plant material into the garden, and practice strict quarantine protocols for new plant acquisitions.\n"
  },
  "Tomato___healthy": {
    organicCure: "General Tips for Maintaining Healthy Tomato Plants:\n\n1. Provide proper sunlight: Tomato plants thrive in full sun, so ensure they receive at least 6-8 hours of direct sunlight per day.\n\n2. Water adequately: Water tomato plants deeply and consistently, keeping the soil evenly moist but not waterlogged.\n\n3. Mulch: Apply organic mulch, such as straw or wood chips, around the base of tomato plants to conserve moisture, suppress weeds, and maintain a stable soil temperature.\n\n4. Balanced nutrition: Use organic fertilizers or compost to provide balanced nutrition to the plants. Follow the product instructions for application rates.\n\n5. Pruning: Remove suckers (auxiliary shoots) that develop in the leaf axils of tomato plants to improve airflow and focus energy on fruit production.\n\n6. Stake or cage the plants: Provide support to tomato plants by staking or caging them to prevent branches from bending or breaking under the weight of the fruit.\n\n7. Monitor for pests and diseases: Regularly inspect plants for any signs of pest infestation or disease. Take appropriate measures at the earliest sign of trouble.\n",
    prevention: ""
  }
};

const App = () => {
  const [selectedFile, setSelectedFile] = useState(null);
  const [selectedAPI, setSelectedAPI] = useState('');
  const [diseaseResult, setDiseaseResult] = useState(null);

  const handleFileDrop = (acceptedFiles) => {
    setSelectedFile(acceptedFiles[0]);
  };

  const handleAPIChange = (event) => {
    setSelectedAPI(event.target.value);
  };

  const handleFileUpload = async () => {
    try {
      const formData = new FormData();
      formData.append('file', selectedFile);

      const response = await axios.post(selectedAPI, formData, {
        headers: {
          'Content-Type': 'multipart/form-data',
        },
      });

      if (response.data) {
        setDiseaseResult(response.data);
      }
    } catch (error) {
      console.log(error);
    }
  };

  const isDiseaseDetected = diseaseResult && !diseaseResult.class.toLowerCase().includes('healthy');
  const isHealthy = !isDiseaseDetected;

  const organicCure = plantDiseases[diseaseResult?.class]?.organicCure;
  const preventionMeasures = plantDiseases[diseaseResult?.class]?.prevention;

  return (
    <div className="container">
      <h1 className="heading">Plant Disease Detector</h1>
      <div className="content">
        <Dropzone onDrop={handleFileDrop} accept="image/*" multiple={false}>
          {({ getRootProps, getInputProps }) => (
            <div className="dropzone" {...getRootProps()}>
              <input {...getInputProps()} />
              {selectedFile ? (
                <div className="selected-file">
                  <p>Selected File:</p>
                  <img src={URL.createObjectURL(selectedFile)} alt="Selected" />
                  <p>{selectedFile.name}</p>
                </div>
              ) : (
                <p>Drag and drop an image file here, or click to select a file</p>
              )}
            </div>
          )}
        </Dropzone>
        <div className="api-dropdown-container">
        <select value={selectedAPI} onChange={handleAPIChange} className="api-dropdown">
          <option value="">Select an API</option>
          <option value=" http://127.0.0.1:8000/predict">Common Plants (Corn, Grape, Bell Pepper, Potato, Tomato)</option>
          <option value=" http://127.0.0.1:8080/predict">Uncommon Plants (Apple, Blueberry, Cherry, Peach, Raspberry, Soybean, Squash, Strawberry)</option>
          {/* Add more options for different APIs */}
        </select>
        </div>
        <button onClick={handleFileUpload} disabled={!selectedFile || !selectedAPI} className="detect-btn">
          Detect Disease
        </button>
      </div>

      {isDiseaseDetected && (
        <div className="result">
          <h2 className="result-heading">Disease Detected</h2>
          <div className="disease-info">
            <p className="disease-name">{diseaseResult.class.replace(/_/g, ' ')}</p>
            <p className="confidence">Confidence: {Math.round(diseaseResult.confidence * 100)}%</p>
          </div>
          <div className="organic-cure">
            <h3>Organic Cure:</h3>
            <ul>
              {organicCure && organicCure.split('\n\n').map((point, index) => (
                <li key={index}>{point}</li>
              ))}
            </ul>
          </div>
          <div className="prevention-measures">
            <h3>Prevention Measures:</h3>
            <ul>
              {preventionMeasures && preventionMeasures.split('\n\n').map((point, index) => (
                <li key={index}>{point}</li>
              ))}
            </ul>
          </div>
        </div>
      )}

      {isHealthy && (
        <div className="result healthy">
          <h2 className="result-heading">Plant is Healthy</h2>
          {diseaseResult && (
      <div className="disease-info">
      <p className="disease-name">{diseaseResult.class.replace(/_/g, ' ')}</p>
      <p className="confidence">Confidence: {Math.round(diseaseResult.confidence * 100)}%</p>
    </div>
    )}
          <p className="healthy-text">No disease detected.</p>
        </div>
      )}
    </div>
  );
};

export default App;
